#! /bin/bash

source .env

DOWNLOAD_URL=https://github.com/pyodide/pyodide/releases/download/${VITE_PYODIDE_VERSION}/pyodide-build-${VITE_PYODIDE_VERSION}.tar.bz2
# DOWNLOAD_URL=https://github.com/pyodide/pyodide/releases/download/0.20.1a1/pyodide-build-0.20.1a1.tar.bz2
# echo $DOWNLOAD_URL
# echo $VITE_PYODIDE_VERSION

TAR_NAME=./pyodide.tar
TAR_BZ2_NAME=${TAR_NAME}.bz2

# using [ expression ] syntax and in place
# of File.txt you can write your file name
if [ -f "${TAR_NAME}" ];
then
    echo "[preinstall] scratch/pyodide.tar.bz2 already downloaded."
    exit;
else
    # if file exist the it will be printed
    echo "[preinstall] Downloading pyodide from github build..."
fi

rm -rf $TAR_NAME $TAR_BZ2_NAME

curl -LJ -o ${TAR_BZ2_NAME} $DOWNLOAD_URL

# Extract archive
# tar -xf ./scratch/pyodide.tar.bz2
# mv pyodide .pyodide
# For installation as tar
bzip2 -kd $TAR_BZ2_NAME
