#! /bin/bash

TAR_NAME=./scratch/pyodide.tar
TAR_BZ2_NAME=${TAR_NAME}.bz2

# using [ expression ] syntax and in place
# of File.txt you can write your file name
if [ -f "${TAR_NAME}" ];
then
    echo "[preinstall] scratch/pyodide.tar already downloaded."
    exit;
then
    # if file exist the it will be printed
    echo "[preinstall] Downloading pyodide from github build..."
fi


mkdir scratch -p
rm -f $TAR_NAME $TAR_BZ2_NAME

curl -LJ -o ${TAR_BZ2_NAME} https://github.com/pyodide/pyodide/releases/download/0.20.1a1/pyodide-build-0.20.1a1.tar.bz2
bzip2 -kd $TAR_BZ2_NAME
